#!/usr/bin/python3
import json
from PIL import Image, ImageDraw, ImageFont

outputname = "meme.png"

font_path = "font/Envy.ttf"
font_size = 50
font = ImageFont.truetype(font_path,font_size)

imgpath = "img/drake_800x800.png"
fn = "img/drake_800x800.json"

data = open(fn).read()
data = json.loads(data)

ta = data['text_areas']

message = ["hello","memaker"]

class TextArea:
    def __init__(self, x1, y1, x2, y2):
        self.x1 = x1
        self.y1 = y1
        self.x2 = x2
        self.y2 = y2

image = Image.open(imgpath)
draw = ImageDraw.Draw(image)

draw.text(xy=(20,20),text="yolo",fill=(0,0,0),font=font)

for i, a in enumerate(ta):
    print(message[i] + " " + str(a))

image.save(outputname)
