#!/usr/bin/python3
import json
from PIL import Image, ImageDraw, ImageFont

outputname = "meme.png"

font_path = "font/Envy.ttf"
font_size = 50
font = ImageFont.truetype(font_path,font_size)

imgpath = "img/drake_800x800.png"
fn = "img/drake_800x800.json"

data = open(fn).read()
data = json.loads(data)

ta = data['text_areas']

message = ["hello","memaker"]

class TextArea:
    def __init__(self, textAreaData):
        self.x1 = textAreaData[0]
        self.y1 = textAreaData[1]
        self.x2 = textAreaData[2]
        self.y2 = textAreaData[3]

image = Image.open(imgpath)
draw = ImageDraw.Draw(image)

def drawText(m, textAreaData):
    textArea = TextArea(textAreaData)

#draw.text(xy=(20,20),text="yolo",fill=(0,0,0),font=font)

for i, a in enumerate(ta):
    x = a[0]
    y = a[1]
    m = message[i]
    draw.text(xy=(x,y),text=m,fill=(0,0,0),font=font)

image.save(outputname)
